version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: voice_agent_user
      POSTGRES_PASSWORD: VoIc3Ag3NT2025
      POSTGRES_DB: voice_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voice_agent_user -d voice_agent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
