version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: voice_agent_user
      POSTGRES_PASSWORD: voiceagent2025
      POSTGRES_DB: voice_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voice_agent_user -d voice_agent"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env  # Explicitly load .env file
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://voice_agent_user:voiceagent2025@postgres:5432/voice_agent
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_PROJECT=voice-agent-prod
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - GOOGLE_CREDENTIALS_FILE=/app/voice-agent-tts-05f49acb929c.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BASE_URL=${BASE_URL}
    volumes:
      - .:/app
      - ./voice-agent-tts-05f49acb929c.json:/app/voice-agent-tts-05f49acb929c.json
    depends_on:
      postgres:
        condition: service_healthy
    command: gunicorn --bind 0.0.0.0:5000 src.api.routes:app

volumes:
  - ./certs:/app/certs
  postgres_data:

  